- name: conditions
  hosts: local
  connection: local
  vars:
    IS_LIVE: false
  tasks:
  - name: check if program is live or not
    ansible.builtin.debug:
      msg: "Program is Live"
    when: IS_LIVE 

   

  