- name: filters example
  hosts: local
  connection: local
  vars:
    topics: linux, shell, ansible, terraform
    tagsmap:
     name: ansible
     project: roboshop
     component: catalogue
    tagslist: [
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "component",
            "value": "catalogue"
        }
    ]
  tasks:
  - name: greeting message
    ansible.builtin.debug:
      msg: "hello divakar, {{ GREETING | default('good morning')}}"

  - name: covert string to list
    ansible.builtin.debug:
      msg: "{{ topics | split(',') }}"

  - name: covert map to list
    ansible.builtin.debug:
      msg: "{{ tagslist| dict2items }}"

  - name: covert list to map
    ansible.builtin.debug:
      msg: "{{ tagslist| items2dict }}"  
